stages:
  prepare_dataset:
    cmd: python repro/repro.py
    deps:
    - raw_datasets/20201005_H_2_anomaly.zip
    - raw_datasets/20201008_H_2_normal.zip
    - repro/check_format.py
    - repro/create_info_csv.py
    - repro/create_mask.py
    - repro/crop_tobu_and_ziku.py
    - repro/merge.py
    - repro/rename.py
    - repro/repro.py
    - repro/unzip.py
    outs:
    - dataset/color_images
    - dataset/gray_images
    - dataset/info.csv
    - dataset/masks
