stages:
  dataset_creator:
    cmd: python3 pipelines/run.py
    deps:
    - pipelines/dataset_creator/__init__.py
    - pipelines/dataset_creator/create_info_csv.py
    - pipelines/dataset_creator/create_mask.py
    - pipelines/dataset_creator/dataset_creator.py
    - pipelines/dataset_creator/extract_zip.py
    - pipelines/dataset_creator/rename_files.py
    - pipelines/run.py
    - zip_dvc/202008131442_H.zip
    outs:
    - zip_dvc/dataset/images
    - zip_dvc/dataset/info.csv
    - zip_dvc/dataset/masks
