dataset:
    train:
      base: ../dataset
      query:
        - is_anomaly_image == 1 &
          crop_type == 'tobu' &
          supervised == 'train'
    test:
      base: ../dataset
      query:
        - crop_type == 'tobu' &
          supervised == 'test'
