name: runs-on-metis
on:
  push:
    branches: [master]
jobs:
  run-ssad:
    runs-on: [self-hosted]
    steps:
      - name: clone
        run: |
          cd ~/github_actions
          git clone git@github.com:TaikiInoue/DVC.git
          git clone git@github.com:TaikiInoue/SSAD.git
      - name: docker-build-run
        run: |
          cd ~/github_actions/SSAD/docker
          make build
          make run
      - name: prepare-dataset
        run: |
          cd /app/github_actions/DVC
          dvc pull data/202008131442_H.zip.dvc
          dvc repro
      - name: run-model
        run: |
          cd /app/github_actions/SSAD/ssad
          python run.py conf/config.yaml
