name: runs-on-metis
on:
  push:
    branches: [ master ]

jobs:
  prepare-data:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: pipeline
        shell: bash
        run: |
          dvc pull data/*.zip.dvc
          dvc repro
          git clone $URL
          cd $PROJECT_NAME
          git reset --hard $SHA1
          docker build docker/ssad/.
          docker run
          dokeer rmi ??
