name: run_ssad_on_metis
on:
  push:
    branches: [master]
jobs:
  run_ssad_on_metis:
    runs-on: [self-hosted]
    steps:
      - name: clone
        run: |
          cd ~/github_actions
          git clone git@github.com:TaikiInoue/DVC.git
          git clone git@github.com:TaikiInoue/SSAD.git
      - name: repro
        run: |
          cd ~/github_actions/DVC/docker
          make build
          make run
      - name: run_ssad
        run: |
          cd ~/github_actions/SSAD/docker
          make build
          make run
      - name: clean-up
        run: |
          rm -rf ~/github_actions/DVC
          rm -rf ~/github_actions/SSAD
