name: runs-on-metis
on:
  push:
    branches: [ master ]

jobs:
  prepare-data:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: pipeline
        shell: bash
        run: |
          docker attach metis-docker
          dvc pull data --run-cache
          dvc repro
          
  run-model:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: |
        docker run 
