name: run_ssad_on_metis
on:
  push:
    branches: [master]
jobs:
  clean_up:
    runs-on: [self-hosted]
    steps:
      - name: clean_up
        run: |
          sudo rm -rf ~/github_actions/DVC
          sudo rm -rf ~/github_actions/SSAD
  run_ssad_on_metis:
    runs-on: [self-hosted]
    needs: clean_up
    steps:
      - name: clone
        run: |
          cd ~/github_actions
          git clone git@github.com:TaikiInoue/DVC.git
          git clone git@github.com:TaikiInoue/SSAD.git
      - name: repro
        run: |
          cd ~/github_actions/DVC/docker
          make build
          make run
      - name: run_ssad
        run: |
          cd ~/github_actions/SSAD/docker
          make build
          make run
